language : c++
sudo : true
dist : trusty

os:
    - linux

compiler : 
    - gcc

addons:
    apt : 
        sources:
            -ubuntu-tool-chain-r-test

before_install:
    - wget https://protobuf.googlecode.com/files/protobuf-3.5.1.tar.gz
    - tar -xvzf protobuf-3.5.1.tar.gz
    - cd protobuf-3.5.1 && ./configure && make && make install

branches:
    master

before_script:
    - mkdir build
    - cd build
    - cmake ..
script :
    - make

    


