language : c++
sudo : true
dist : trusty

os:
    - linux

compiler : 
    - gcc

addons:
    apt : 
        sources:
            -ubuntu-tool-chain-r-test

before_install:
    - sudo apt-get install libprotobuf-dev protobuf-compiler 

branches:
    master

before_script:
    - mkdir build
    - cd build
script :
    - cmake ..

    


