language : c++
sudo : true
dist : trusty

os:
    - linux

compiler : 
    - gcc

addons:
    apt : 
        sources:
            -ubuntu-tool-chain-r-test

before_install:
    - wget https://github.com/google/protobuf/archive/v3.5.1.zip
    - unzip v3.5.1.zip
    - cd protobuf-3.5.1 && git submodule update --init --recursive && ./autogen.sh && ./configure && make && sudo make install

branches:
    master

before_script:
    - mkdir build
    - cd build
    - cmake ..
script :
    - make

    


