language : c++
sudo : false
dist : trusty

os:
    - linux

compiler : 
    - gcc

addons:
    apt : 
        sources:
            -ubuntu-tool-chain-r-test

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libprotobuf-dev protobuf-compiler 

branches:
    master

before_script:
    - mkdir build
    - cd build
    - cmake ..

script :
    - make

    


